import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export interface Vulnerability {
  id: string;
  severity: 'high' | 'medium' | 'low' | 'info';
  confidence?: 'High' | 'Medium' | 'Low';
  title: string;
  description: string;
  recommendation?: string;
  cwe?: string;
  owasp?: string;
}

export interface ScanResult {
  scanId: string;
  completedAt: string;
  totalIssues: number;
  highSeverity: number;
  mediumSeverity: number;
  lowSeverity: number;
  informational: number;
  vulnerabilities: Vulnerability[];
  passedChecks: number;
}

export interface SecurityScanRequest {
  id: string;
  name: string;
  method: string;
  url: string;
}

export const downloadSecurityScanAsPDF = async (
  elementId: string,
  filename: string
) => {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error('Element not found for PDF export');
    return;
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: '#ffffff',
      useCORS: true,
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');

    const pdfW = pdf.internal.pageSize.getWidth();
    const pdfH = pdf.internal.pageSize.getHeight();

    const imgW = pdfW;
    const imgH = (canvas.height * imgW) / canvas.width;

    let heightLeft = imgH;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgW, imgH);
    heightLeft -= pdfH;

    while (heightLeft > 0) {
      position = heightLeft - imgH;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgW, imgH);
      heightLeft -= pdfH;
    }

    pdf.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

export const downloadSecurityScanAsHTML = (
  scanResult: ScanResult,
  request: SecurityScanRequest,
  filename: string
) => {
  try {
    const htmlContent = buildSecurityScanHTMLDocument(scanResult, request);

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  } catch (err) {
    console.error('Error generating HTML:', err);
    throw err;
  }
};

export const shareSecurityScan = async (
  scanResult: ScanResult,
  request: SecurityScanRequest
) => {
  const summaryText = `🛡️ Security Scan Results

📋 Scan Details:
• Name: ${request.name}
• Endpoint: ${request.method} ${request.url}
• Completed: ${new Date(scanResult.completedAt).toLocaleString()}

📊 Summary:
• Total Issues: ${scanResult.totalIssues}
• High Severity: ${scanResult.highSeverity}
• Medium Severity: ${scanResult.mediumSeverity}
• Low Severity: ${scanResult.lowSeverity}
• Informational: ${scanResult.informational}
• Passed Checks: ${scanResult.passedChecks}

Generated by Optraflow Security Scanner (powered by ZAP Proxy)`;

  if (navigator.share && navigator.canShare) {
    const shareData = {
      title: `Security Scan: ${request.name}`,
      text: summaryText,
    };

    if (navigator.canShare(shareData)) {
      try {
        await navigator.share(shareData);
        return { method: 'shared', success: true };
      } catch (error) {
        if ((error as Error).name === 'AbortError') {
          return { method: 'cancelled', success: false };
        }
        console.warn('Share failed, falling back to clipboard:', error);
      }
    }
  }

  if (navigator.clipboard && navigator.clipboard.writeText) {
    try {
      await navigator.clipboard.writeText(summaryText);
      return { method: 'clipboard', success: true };
    } catch (error) {
      console.error('Clipboard write failed:', error);
    }
  }

  const textarea = document.createElement('textarea');
  textarea.value = summaryText;
  textarea.style.position = 'fixed';
  textarea.style.opacity = '0';
  document.body.appendChild(textarea);
  textarea.select();

  try {
    const success = document.execCommand('copy');
    document.body.removeChild(textarea);
    return { method: 'execCommand', success };
  } catch (error) {
    document.body.removeChild(textarea);
    console.error('Copy command failed:', error);
    prompt('Copy this summary:', summaryText);
    return { method: 'prompt', success: false };
  }
};

const escapeHtml = (s: string) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const getSeverityStyle = (
  severity: string
): { bg: string; color: string; border: string; icon: string } => {
  const styles: Record<
    string,
    { bg: string; color: string; border: string; icon: string }
  > = {
    high: { bg: '#fef2f2', color: '#991b1b', border: '#fecaca', icon: '⚠️' },
    medium: { bg: '#fff7ed', color: '#9a3412', border: '#fed7aa', icon: '⚠️' },
    low: { bg: '#f0f9ff', color: '#0c4a6e', border: '#bae6fd', icon: 'ℹ️' },
    info: { bg: '#fefce8', color: '#854d0e', border: '#fde047', icon: 'ℹ️' },
  };
  return styles[severity] || styles.info;
};

const getSeverityBadgeStyle = (
  severity: string
): { bg: string; color: string } => {
  const styles: Record<string, { bg: string; color: string }> = {
    high: { bg: '#ef4444', color: '#ffffff' },
    medium: { bg: '#f97316', color: '#ffffff' },
    low: { bg: '#0ea5e9', color: '#ffffff' },
    info: { bg: '#eab308', color: '#ffffff' },
  };
  return styles[severity] || styles.info;
};

const buildSecurityScanHTMLDocument = (
  scanResult: ScanResult,
  request: SecurityScanRequest
): string => {
  const formatDate = (d: string) => new Date(d).toLocaleString();

  const vulnerabilitiesHTML = scanResult.vulnerabilities
    .map((vuln) => {
      const style = getSeverityStyle(vuln.severity);
      const badgeStyle = getSeverityBadgeStyle(vuln.severity);

      return `
        <div style="border:1px solid ${
          style.border
        };border-radius:12px;margin-bottom:20px;overflow:hidden;background:${
        style.bg
      };">
          <!-- Header -->
          <div style="padding:16px 20px;display:flex;justify-content:space-between;align-items:flex-start;gap:16px;">
            <div style="display:flex;align-items:flex-start;gap:12px;flex:1;">
              <span style="font-size:20px;margin-top:2px;">${style.icon}</span>
              <h4 style="font-size:16px;font-weight:600;color:#111827;margin:0;line-height:1.4;">${escapeHtml(
                vuln.title
              )}</h4>
            </div>
            <div style="display:flex;gap:8px;align-items:center;flex-shrink:0;">
              ${
                vuln.confidence
                  ? `
                <span style="padding:4px 10px;border-radius:6px;font-size:11px;font-weight:500;background:#f3f4f6;color:#374151;border:1px solid #e5e7eb;">
                  confidence: ${vuln.confidence}
                </span>
              `
                  : ''
              }
              <span style="padding:4px 12px;border-radius:6px;font-size:12px;font-weight:600;background:${
                badgeStyle.bg
              };color:${badgeStyle.color};text-transform:uppercase;">
                ${vuln.severity}
              </span>
            </div>
          </div>
          
          <!-- Content - Always Expanded -->
          <div style="padding:0 20px 20px 52px;">
            <!-- Description -->
            <div style="margin-bottom:16px;">
              <h5 style="font-size:13px;font-weight:600;color:#374151;margin:0 0 8px 0;text-transform:uppercase;letter-spacing:0.5px;">Description</h5>
              <p style="font-size:14px;color:#4b5563;margin:0;line-height:1.6;">${escapeHtml(
                vuln.description
              )}</p>
            </div>
            
            ${
              vuln.recommendation
                ? `
              <!-- Recommendation -->
              <div style="margin-bottom:16px;">
                <h5 style="font-size:13px;font-weight:600;color:#374151;margin:0 0 8px 0;text-transform:uppercase;letter-spacing:0.5px;">Recommendation</h5>
                <p style="font-size:14px;color:#4b5563;margin:0;line-height:1.6;">${escapeHtml(
                  vuln.recommendation
                )}</p>
              </div>
            `
                : ''
            }
            
            <!-- Tags -->
            <div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px;">
              ${
                vuln.confidence
                  ? `
                <span style="padding:4px 10px;border-radius:6px;font-size:12px;font-weight:500;background:#ffffff;color:#374151;border:1px solid #d1d5db;">
                  Confidence: ${vuln.confidence}
                </span>
              `
                  : ''
              }
              ${
                vuln.cwe
                  ? `
                <span style="padding:4px 10px;border-radius:6px;font-size:12px;font-weight:500;background:#ffffff;color:#374151;border:1px solid #d1d5db;">
                  CWE: ${escapeHtml(vuln.cwe)}
                </span>
              `
                  : ''
              }
            </div>
            
            ${
              vuln.owasp
                ? `
              <!-- OWASP References -->
              <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:12px;">
                <p style="font-size:12px;color:#6b7280;margin:0;word-break:break-all;line-height:1.5;">
                  <strong>OWASP:</strong> ${escapeHtml(vuln.owasp)}
                </p>
              </div>
            `
                : ''
            }
          </div>
        </div>
      `;
    })
    .join('');

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Security Scan Report - ${escapeHtml(request.name)}</title>
      <style>
        *{box-sizing:border-box}
        body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Roboto',sans-serif;margin:0;padding:24px;background:#f8fafc;line-height:1.5;color:#1f2937}
        .report-container{max-width:900px;margin:0 auto}
        @media print{
          body{background:#fff;padding:0}
          .report-container{max-width:none}
        }
      </style>
    </head>
    <body>
      <div class="report-container">
        <!-- Header -->
        <div style="background:#ffffff;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,0.1);padding:32px;margin-bottom:24px;">
          <div style="display:flex;justify-content:space-between;align-items:start;margin-bottom:24px;">
            <div>
              <h1 style="font-size:28px;font-weight:700;color:#111827;margin:0 0 8px 0;">
                🛡️ Security Scan Report
              </h1>
              <p style="font-size:18px;color:#374151;margin:0 0 8px 0;font-weight:500;">
                ${escapeHtml(request.name)}
              </p>
              <p style="font-size:14px;color:#6b7280;margin:0;">
                <span style="padding:3px 8px;background:#dbeafe;color:#1e40af;border-radius:4px;font-weight:600;font-size:12px;">
                  ${escapeHtml(request.method)}
                </span>
                <span style="margin-left:8px;">${escapeHtml(request.url)}</span>
              </p>
            </div>
            <div style="text-align:right;">
              <h2 style="font-size:22px;font-weight:700;color:#2563eb;margin:0;">Optraflow</h2>
              <p style="font-size:13px;color:#6b7280;margin:4px 0 0 0;">Security Analysis</p>
            </div>
          </div>

          <div style="display:flex;align-items:center;gap:8px;padding:12px 16px;background:#f0f9ff;border-left:4px solid #3b82f6;border-radius:6px;">
            <span style="font-size:14px;color:#1e40af;">
              ⏱️ Completed: ${formatDate(scanResult.completedAt)}
            </span>
          </div>
        </div>

        <!-- Summary Cards -->
        <div style="display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin-bottom:24px;">
          <div style="background:#ffffff;border-radius:10px;box-shadow:0 1px 3px rgba(0,0,0,0.1);padding:16px;text-align:center;">
            <p style="font-size:11px;color:#6b7280;margin:0 0 6px 0;font-weight:600;text-transform:uppercase;">Total Issues</p>
            <p style="font-size:26px;font-weight:700;color:#111827;margin:0;">${
              scanResult.totalIssues
            }</p>
          </div>
          
          <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:10px;padding:16px;text-align:center;">
            <p style="font-size:11px;color:#991b1b;margin:0 0 6px 0;font-weight:600;text-transform:uppercase;">High</p>
            <p style="font-size:26px;font-weight:700;color:#dc2626;margin:0;">${
              scanResult.highSeverity
            }</p>
          </div>
          
          <div style="background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:16px;text-align:center;">
            <p style="font-size:11px;color:#9a3412;margin:0 0 6px 0;font-weight:600;text-transform:uppercase;">Medium</p>
            <p style="font-size:26px;font-weight:700;color:#ea580c;margin:0;">${
              scanResult.mediumSeverity
            }</p>
          </div>
          
          <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:10px;padding:16px;text-align:center;">
            <p style="font-size:11px;color:#0c4a6e;margin:0 0 6px 0;font-weight:600;text-transform:uppercase;">Low</p>
            <p style="font-size:26px;font-weight:700;color:#0284c7;margin:0;">${
              scanResult.lowSeverity
            }</p>
          </div>
          
          <div style="background:#fefce8;border:1px solid #fde047;border-radius:10px;padding:16px;text-align:center;">
            <p style="font-size:11px;color:#854d0e;margin:0 0 6px 0;font-weight:600;text-transform:uppercase;">Info</p>
            <p style="font-size:26px;font-weight:700;color:#ca8a04;margin:0;">${
              scanResult.informational
            }</p>
          </div>
          
          <div style="background:#f0fdf4;border:1px solid #86efac;border-radius:10px;padding:16px;text-align:center;">
            <p style="font-size:11px;color:#166534;margin:0 0 6px 0;font-weight:600;text-transform:uppercase;">Passed</p>
            <p style="font-size:26px;font-weight:700;color:#059669;margin:0;">${
              scanResult.passedChecks
            }</p>
          </div>
        </div>

        <!-- Vulnerabilities -->
        <div style="background:#ffffff;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,0.1);padding:24px;margin-bottom:24px;">
          <h2 style="font-size:18px;font-weight:700;color:#111827;margin:0 0 20px 0;">
            🔍 Detected Vulnerabilities (${scanResult.vulnerabilities.length})
          </h2>
          ${
            vulnerabilitiesHTML ||
            '<p style="text-align:center;color:#6b7280;padding:40px 0;">✅ No vulnerabilities detected</p>'
          }
        </div>

        <!-- Footer -->
        <div style="text-align:center;padding:24px;color:#9ca3af;font-size:13px;">
          <p style="margin:0;">Generated by <strong style="color:#6b7280;">Optraflow Security Scanner</strong></p>
          <p style="margin:6px 0 0 0;">Powered by ZAP Proxy • Report generated on ${new Date().toLocaleString()}</p>
        </div>
      </div>
    </body>
    </html>
  `;
};
